---
title: "quantitative strategy research using R"
author: "Ru JIA"
date: "2016-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 一个最简单的CTA策略

## 策略逻辑
- 趋势追踪策略。以低成本反复试探，试图捕捉大趋势。
- 价格突破前30天最高价开多、价格突破前30天最低价开空。
- 1%移动止损。

两个参数：`N = 30`, `lossrate = 0.01`

## 回测信息

- 回测品种：螺纹钢连续合约rb
- 回测时间段： 2010-01-01 ~ 2016-10-21
- 采用日度数据

## 写策略

```{r}
rm(list = ls())
library(data.table)
library(rlist)
library(pipeR)
library(ggplot2)

load("data/rb_dominant_daily.rda")

# 参数取值
N = 30
lossrate = .01

# 手续费 & 滑点
fee.rate <- 8e-5  #手续费单边万分之8
slippage <- 2 * 1  # 滑点2个tick * 最小变动价位1

# 生成N_high, N_low
dt[, `:=`(
  N_high = shift(TTR::runMax(high, n = N), n = 1, type = "lag"),
  N_low = shift(TTR::runMin(low, n = N), n = 1, type = "lag")
)]

# # see signals
# dt[, long_signal := high > N_high]
# dt[, short_signal := low < N_low]
# View(dt)
# 
# library(ggplot2)
# dt[, time_index := 1:.N]
# p <- ggplot(dt, aes(x = time_index, ymin = low, ymax = high))+ 
#   geom_ribbon(aes(ymin = N_low, ymax = N_high), fill = alpha("yellow", .7)) + 
#   geom_linerange()
# p


# 初始化
ptr <- 1L
position <- 0L
stop_price <- NA_real_
closed_profit <- 0.0
position_profit <- 0.0
fee <- 0.0
out <- list()  # 逐日账户状态，list of list
trades <- list()  # 逐笔交易记录，list of list


bar <- function(w){
  dt[[w]][ptr]
}

# 循环
for(ptr in 1:nrow(dt))
{
  # PART 0. 数据准备
  high <- bar("high")
  low <- bar("low")
  sig_long <- bar("high") > bar("N_high")
  sig_short <- bar("low") < bar("N_low")
  
  if (is.na(sig_short) | is.na(sig_long)) next  # 跳过前N个
  
  # PART 1. 检查止损，更新止损点
  if (position == 1L) {
    stopifnot(!is.na(stop_price)) 
    if (low < stop_price) {
      # 平掉现有仓位
      leave_price <- stop_price - slippage
      closed_profit <- closed_profit + (leave_price - enter_price)
      fee <- fee + leave_price * fee.rate
      position_profit <- 0.0
      # 添加交易记录
      trade_out <- list(
        enter_date = enter_date,
        enter_price = enter_price,
        leave_date = bar("date"),
        leave_price = leave_price,
        side = position,
        commission = leave_price * fee.rate + enter_price * fee.rate
      ) 
      trades <- list.append(trades, trade_out)
      rm(trade_out)
      
      # 重置状态变量
      position <- 0L
      stop_price <- NA_real_
      enter_price <- NA_real_
      
    } else {
      # 更新止损点
      stop_price <- max(stop_price, high * (1 - lossrate))
    }
    
  } else if (position == -1L) {
    stopifnot(!is.na(stop_price)) 
    if (high > stop_price) {
      # 平掉现有仓位
      leave_price <- stop_price + slippage
      closed_profit <- closed_profit + (enter_price - leave_price)
      fee <- fee + leave_price * fee.rate
      position_profit <- 0.0
      
      # 添加交易记录
      trade_out <- list(
        enter_date = enter_date,
        enter_price = enter_price,
        leave_date = bar("date"),
        leave_price = leave_price,
        side = position,
        commission = leave_price * fee.rate + enter_price * fee.rate
      ) 
      trades <- list.append(trades, trade_out)
      rm(trade_out)
      
      # 重置状态变量
      position <- 0L
      stop_price <- NA_real_
      enter_price <- NA_real_
      
    } else {
      stop_price <- min(stop_price, low * (1 + lossrate))
    }
  }
  
  # PART 2. 处理开仓信号
  if (position == 0L) {
    # 情况1：没有任何仓位
    if (sig_long & !sig_short) {
      # 情况1.1：开多
      enter_price <- max(bar("N_high"), bar("open")) + slippage  # 入场价格
      enter_date <- bar("date")  # 记录入场时间
      stop_price <- enter_price * (1 - lossrate)  # 设好止损价
      position <- 1L
      fee <- fee + enter_price * fee.rate
    } else if (sig_short & !sig_long) {
      # 情况1.2：开空
      enter_price <- min(bar("N_low"), bar("open")) - slippage # 入场价格
      enter_date <- bar("date")  # 记录入场时间
      stop_price <- enter_price * (1 + lossrate)  # 设好止损价
      position <- -1L
      fee <- fee + enter_price * fee.rate
    } else if (sig_long & sig_short) {
      # 情况1.3：(极其少见)多空信号都出现了
      # you may add some message ...
    } else {
      # 情况1.4：既没有开多信号，也没有开空信号。
      # pass
    }
    
  } else if (position == 1L) {
    # 情况2：持有多仓
    # 持有多仓的情况下出现了开空信号：平掉现有的仓位，再反向开仓
    # pass
  } else if (position == -1L){
    # 情况3：持有空仓 
  } else {
    warning("101")
  }
  
  # PART 3. 保存信息至out变量
  position_profit <- ifelse(position == 0L, 
                            0.0, 
                            position * (bar("close") - enter_price)
                            ) # 计算持仓浮动盈亏
  bar_out <- list(
    date = bar("date"),
    position = position,
    closed_profit = closed_profit,
    position_profit = position_profit
  )
  out <- list.append(out, bar_out)
  #message(ptr)
}

out_dt <- list.stack(out, data.table = TRUE)
out_dt[, net_profit := closed_profit + position_profit - fee]
#View(out_dt)
trades_dt <- list.stack(trades, data.table = TRUE)
trades_dt[, profit := side * (leave_price - enter_price) - commission]
View(trades_dt)

plot(out_dt$net_profit, type = "l")
plot(out_dt$position, type = "h")
hist(trades_dt$profit, breaks = 50)
```



## 计算策略评价指标，自动生成报告


## 参数敏感性分析


## 一些问题
- 数据问题，没有处理主力合约换月，而是简单地拼接起来当做一个合约
- 简单起见，不考虑仓位调整问题，都是一手
